beta testing

diff --git a/github/workflows/build.yml b/github/workflows/build.yml
--- a/github/workflows/build.yml
+++ b/github/workflows/build.yml
@@ -14,6 +14,11 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
+      - name: Debug Buildozer
+        run: |
+          which buildozer || echo "Buildozer not found!"
+          buildozer --version || echo "Buildozer version check failed!"
+
       - name: Install Dependencies
         run: |
           sudo apt update
